spring:
  application:
    name: grpc
  
  datasource:
      url: jdbc:mysql://localhost:3306/medicash
      username: admin
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver class name

  flyway:
    enable: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    show-sql: true
