-- MySQL syntax

CREATE TABLE IF NOT EXISTS `users` (
    `id` VARCHAR(36) NOT NULL PRIMARY KEY,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET `utf8mb4`;